import React from 'react';
import { appWithI18Next } from 'ni18n';
import '../styles/globals.css';
import Head from 'next/head';
import type { AppProps } from 'next/app';

import { ni18nConfig } from '../ni18n.config';

function Stellr({ Component, pageProps }: AppProps) {
  return (
    <div className="app">
      <Head>
        <title>Stellr</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </div>
  );
}

export default appWithI18Next(Stellr, ni18nConfig);
